main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

newstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7', include('story7.urls')),
    path('story8', include('story8.urls')),
    path('halo', include('story9.urls')),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('/data', views.fungsi_buku, name='data'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('/login', views.login_page, name='login'),
    path('/signup', views.signup_page, name='signup'),
    path('', views.logout_page, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7/story7.html')

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

def story8(request):
    response = {}
    return render(request, 'story8/story8.html', response)

def fungsi_buku(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    result = requests.get(url)
    data = json.loads(result.content)
    return JsonResponse(data, safe=False)
    

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .models import Profile
from .forms import LoginForm, RegisterForm
 
User = get_user_model()


def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Wrong Password!')
            print("error.......")
    else:
        messages.error(request, 'Wrong username!')
    return render(request, "story9/login.html", context=context)

def signup_page(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        messages.success(request, f'Account {username} has been created. Please Log In!')
        return redirect("/halo/login")
    return render(request, "story9/signup.html", context=context)

def logout_page(request):
    logout(request)
    return render(request, "main/home.html")

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock meta %}

{% block content %}



<div class="text-align-center" id="welcome">
 <div class="centered" id="first">  
  <div class="row mt-5">
      <div class="col-md-1 col-sm-1"> </div>
      <div class="col-md-11 col-sm-11 mt-5">
        {% if user.is_authenticated %}
        <p class="hometext mt-5">
          Hello <span style="color: rgb(230, 62, 90);">{{user.username}}</span>,<br>This is Ferika's PPW Stroies<br>Do you want to see my stories?<br>Just clik what you want to see <br> on the navigatian bar!
          <br>
          <a href="{% url 'story9:logout'%}">Log Out<img src="{% static 'donut.png' %}" width="50px">
        </p>        
        {% else %}
        <p class="hometext mt-5">
          Hello there,<br>This is Ferika's PPW Stroies<br>Do you want to see my stories?<br><span href="{% url 'story9:login'%}">Log In first!</span>
          <br>Don't have an account? <span href="{% url 'story9:signup'%}">Sign Up!</span>

          <br>
          <a href="{% url 'story9:signup'%}">Sign Up<img src="{% static 'rainbow.png' %}" width="50px"> |</a> <a href="{% url 'story9:login'%}"> Log In<img src="{% static 'stars.png' %}" width="50px"></a>
        </p> 
        
        {% endif %}
         
      </div>
    </div>
  </div>
</div>


<div class="row m-5 justify-content-center">
    <div class="col-md-8 col-sm-8 text-center">
        <div class="spinner-grow text-primary" role="status">
            <span class="sr-only">Loading...</span>
          </div> 
          <div class="spinner-grow text-success" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow text-danger" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow text-warning" role="status">
            <span class="sr-only">Loading...</span>
          </div>
          <div class="spinner-grow text-info" role="status">
            <span class="sr-only">Loading...</span>
          </div>

    </div>
   
</div>


{% endblock content %}

story7/templates/story7/story7.html
{% extends 'base.html' %} {% load static %} {% block meta %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'jquery-3.5.1.js' %}"></script>
        <title>Story7</title> 
        <script src="{% static 'story7.js' %}"></script>
{% endblock meta %}   {% block content %}

  <div class="row m-5  justify-content-center">
      <div class="col-md-2 col-sm-2"></div>
      <div class="col-md-8 col-sm-8 mt-5 text-center ">
          <h4 id="atas">Want to know more about me?<img src="{% static 'stars.png' %}" width="30px"></h4> 
          <h4><img src="{% static 'stars.png' %}" width="30px">Tap the accordion to see the details!</h4>
      </div>
      <div class="col-md-2 col-sm-2 mt-5"><img src="{% static 'sun.png' %}" width="70px"></div>
  </div>

  <div class="container" style="font-family: 'Playfair Display', serif; ">
          <div id="accord-1">
              <h3>Activities <img src="{% static 'rainbow.png' %}" width="30px">
                  <span style="float: right;">
                      <button style="font-size: 20px;" class="button-up" ><i class="fas fa-angle-up"></i></button>
                      <button style="font-size: 20px;" class="button-down" ><i class="fas fa-angle-down"></i></button>
                  </span>
              </h3>
              <div class="isi-1">
                  <table class="table table-hover">
                      <tbody>
                        <tr>
                          <td>Kuliah</td>
                        </tr>
                        <tr>
                          <td>Ikut Kepanitiaan</td>
                        </tr>
                        <tr>
                          <td>haha hihi</td>
                        </tr>
                      </tbody>
                    </table>             
              </div>
          </div>

          <div id="accord-2">
              <h3>Experiences <img src="{% static 'tv.png' %}" width="30px">
                  <span style="float: right;">
                      <button class="button-up" style="font-size: 20px;"><i class="fas fa-angle-up"></i></button>
                      <button class="button-down" style="font-size: 20px;"><i class="fas fa-angle-down"></i></button>
                  </span>
              </h3>
              <div class="isi-2">
                  <table class="table table-hover">
                      <tbody>
                        <tr>
                          <td><a href="https://perak.cs.ui.ac.id/">Secretary of PERAK Fasilkom UI</a></td>
                          <td>2019 - now</td>
                        </tr>
                        <tr>
                          <td><a href="https://compfest.id/">Staff of  Stage Compfest Fasilkom UI</a></td>
                          <td>2019 - now</td>
                        </tr>
                        <tr>
                          <td><a href="https://oh.cs.ui.ac.id/">Staff of  Dankom Open House Fasilkom UI</a></td>
                          <td>2020 - now</td>
                        </tr>
                        <tr>
                          <td><a href="">Secretary of Wisuda Ganjil 2021 Fasilkom UI</a></td>
                          <td>2020 - now</td>
                        </tr>
                      </tbody>
                    </table>           
              </div>
          </div>

          <div id="accord-3">
              <h3>Hobbies <img src="{% static 'game.png' %}" width="30px">
                  <span style="float: right;">
                      <button class="button-up" style="font-size: 20px;"><i class="fas fa-angle-up"></i></button>
                      <button class="button-down" style="font-size: 20px;"><i class="fas fa-angle-down"></i></button>
                  </span>
              </h3>
              <div class="isi-3">
                  <table class="table table-hover">
                      <tbody>
                        <tr>
                          <td>Watch films</td>
                        </tr>
                        <tr>
                          <td>Playing badminton</td>
                        </tr>
                        <tr>
                          <td>Hang out</td>
                        </tr>
                      </tbody>
                    </table>          
              </div>
          </div>

          <div id="accord-4">
              <h3>Happiness <img src="{% static 'donut.png' %}" width="30px">
                  <span style="float: right;">
                      <button class="button-up" style="font-size: 20px;"><i class="fas fa-angle-up"></i></button>
                      <button class="button-down" style="font-size: 20px;"><i class="fas fa-angle-down"></i></button>
                  </span>
              </h3>
              <div class="isi-4">
                <table class="table table-hover">
                  <tbody>
                      <tr>
                        <td>CATS</td>
                      </tr>
                  </tbody>
                  </table>                
            </div>
        </div>

  </div>

  <div class="row m-2  justify-content-center">
    <div class="col-md-2 col-sm-2"></div>
    <div class="col-md-8 col-sm-8 mt-5 ">
      <img src="{% static 'cloudy.png' %}" width="80px">
    </div>
    <div class="col-md-2 col-sm-2 mt-5"></div>
</div>




{% endblock content %}

story8/templates/story8/story8.html
{% extends 'base.html' %} {% load static %} {% block meta %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'jquery-3.5.1.js' %}"></script>
        <title>Story8</title> 
        <script src="{% static 'story8.js' %}"></script>
        

{% endblock meta %}   {% block content %}


<div class="section m-5">
    <div class="row mt-5"></div>
    <div class="search-box m-5" style="margin-top: 50px; display: block;">
        <div class="search-box-logo">
        </div>
        <input type="text" class="form-control" id="search" placeholder="Masukkan judul buku">
    </div>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10 col-sm-10 col-lg-10">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th id="cover" scope="col">Cover</th>
                        <th id="title" scope="col">Title</th>
                        <th id="author" scope="col">Author</th>
                    </tr>
                </thead>
                <tbody>
        
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock content %}

story9/templates/story9/login.html
{% extends 'base.html' %} {% load static %} {% block meta %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>Log In</title> 
        

{% endblock meta %}   {% block content %}

        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8 mt-5" style="color: rgb(0, 64, 121); font-weight: 700;">
                <!-- {% for message in messages %}
                <script>
                    alert("{{ message }}")
                </script>
                {% endfor %} -->
            
                <form method="POST">

                    {% csrf_token %}
                    {{ form.as_p }}
                
                    <button style="background-color:rgb(80, 158, 226);" type="submit" class="btn btn-primary">Login</button>
                
                </form>
            </div>
        </div>
        <div class="row m-5 justify-content-center">
            <div class="col-md-8 col-sm-8">
                <h5 style="color: rgb(167, 69, 212);">Don't have an account? <a href="{% url 'story9:signup'%}">Sign up</a></h5>
            </div>        
        </div>
{% endblock content %}

story9/templates/story9/signup.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<title>Log In</title> 


{% endblock meta %}   {% block content %}

  <body style="background-color: #F3F3F3;">
    <div class="row m-5 justify-content-center">
        <div class="col text-center">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <h5 style="color: black;" {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </h5>
                {% endfor %}
            </ul>
            {% endif %}     
        </div>
    </div>
    
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8"  style="color: rgb(0, 64, 121); font-weight: 700;">
            <form method="POST">

                {% csrf_token %}
            
                {{ form.as_p }}
            
                <button type="submit" class="btn btn-primary" style="background-color: rgb(233, 93, 116);">Register</button>
            
            </form>
        </div>        
    </div>
    <div class="row m-5 justify-content-center">
        <div class="col-md-8 col-sm-8">
            <h5 style="color: rgb(185, 67, 92);">Already have an account? <a href="{% url 'story9:login'%}">Sign in</a></h5>
        </div>   
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;669;800;900&display=swap" rel="stylesheet">
  <!--Icon-->
  <link rel="icon" type="image/png" href="{% static 'rose.png' %}">
  <!-- Bootstrap CSS -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <script src='https://kit.fontawesome.com/a076d05399.js'></script>


  {% block meta %}
  {% endblock meta %}
</head>

<body style="font-family: 'Playfair Display', serif;   background-color: rgb(255, 254, 217);">
  <!-- Navigation Bar -->
<div class="offset-1 col-10 text-center">
  <nav class="navbar fixed-top navbar-expand-lg navbar-light">
      <a class="navbar-brand active" href="{% url 'main:home' %}">Ferika <img src="{% static 'rose.png' %}" width="30px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
          <a style="color: rgb(197, 1, 83);" class="nav-link" href="{% url 'main:home' %}">Home</a>
          </li>
          <li class="nav-item">
          <a style="color: rgb(197, 1, 83);" class="nav-link" href="https://ferikahafshah.herokuapp.com/">Story1-6</a>
          </li>
          <li class="nav-item">
          <a  style="color: rgb(197, 1, 83);" class="nav-link" href="{% url 'story7:story7' %}">Story 7 </a>
          </li>
          <li class="nav-item">
            <a style="color: rgb(197, 1, 83);" class="nav-link" href="{% url 'story8:story8' %}">Story 8</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">Hello {{user.username}}</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'story9:logout' %}">Log out <img src="{% static 'donut.png' %}" width="30px"></a>
          </li>

        {% else %}
          <li class="nav-item">
            <a style="color: rgb(197, 1, 83);" class="nav-link" href="{% url 'main:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:login' %}">Log in<img src="{% static 'stars.png' %}" width="30px"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story9:signup' %}">Sign Up<img src="{% static 'rainbow.png' %}" width="30px"></a>
          </li>
     
        {% endif %}
      </ul>
      </div>
  </nav>
  </div>
  <!-- <section class="hello" id="hello"> -->
  {% block content %}
  {% endblock content %}
  <!-- </section> -->

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>

</html>